# DeepSeek-OCR MCP Server Configuration

server:
  name: deepseek-ocr-runpod
  log_level: INFO
  log_file: /workspace/deepseek_mcp/server.log

model:
  path: /workspace/models/deepseek-vl2
  device: cuda
  dtype: float16
  cache_dir: /workspace/cache

compression:
  default_level: medium
  levels:
    low:
      quality: 0.6
      speed: fast
    medium:
      quality: 0.8
      speed: balanced
    high:
      quality: 0.95
      speed: slow

performance:
  max_batch_size: 1
  timeout_seconds: 30
  enable_caching: true
